### ISSUE TITLE
Title and Text Font Size

### ISSUE THREAD

**Issue by Vitiumartis** [SimonGolms/ngx-ionic-image-viewer#19]
Hi,
how can I change  the font size of title and text?  
With size="small" works not? Thx.
`<ion-img-viewer title="" text="" src="" >`

**Comment by SimonGolms** [comment]
Hi @Vitiumartis, thanks for the question.
With the latest release (#20) of version 0.6.0 you can now set the size of title and text by yourself.

Option 1: Using the input property `titleSize`
`<ion-img-viewer title="My Title" titleSize="small" src="image.png" />`

Option 2: Via the input property `cssClass`, where you enter the respective css class, which will be passed to the viewer component. It is identically to the ionic [modal](https://ionicframework.com/docs/api/modal) component.
```css
// global.scss
.my-custom-image-viewer {
  ion-header {
    ion-title {
      font-size: 18px;
      color: red;
    }
  }

  ion-footer {
    ion-text {
      font-size: 10px;
      color: blue;
    }
  }
}
```
```html
// home.page.html
<ion-img-viewer title="My Title" text="My Aweseome Image" cssClass="my-custom-image-viewer" src="image.png" />
```
